### ISSUE TITLE
1.20.1 Forge 47.3.0 Mixin

### ISSUE THREAD

**Issue by Krimatoria** [ITsMrToad/EBEReforged#1]
But this line says about the Redirector. That's the version I have of him.
Redirector redirector-5.0.0.jar
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: 

I added your mod to a large build and the game crashed. Everything works without him. There are a lot of mods + the connector is still working. But apparently, something is in conflict with something. I could check later, try to find the mod that causes the incompatibility.

https://gist.github.com/Krimatoria/1f81ac81bc6fe13500f9c2c10d3515c5 - Crash Log

1. EBE-1.20-1.20.1-0.3A.jar
2. Redirector redirector-5.0.0.jar
3. ConnectorExtras-1.11.2+1.20.1.jar
4. Connector-1.0.0-beta.45+1.20.1.jar
5. rubidium-extra-0.5.4.3+mc1.20.1-build.121.jar
6. embeddium-0.3.30+mc1.20.1.jar
7. embeddiumplus-1.20.1-v1.2.13.jar
8. oculus-mc1.20.1-1.7.0.jar

**Comment by ITsMrToad** [comment]
The Forgified fabric api causes a crash. The FRAPI (Fabric rendering api) is built-in module of EBE, and because of this they are not compatible.

**Comment by Krimatoria** [comment]
> The Forgified fabric api causes a crash. The FRAPI (Fabric rendering api) is built-in module of EBE, and because of this they are not compatible.

It's a connector, I wonder if it's possible to fix it on their side?

**Comment by ITsMrToad** [comment]
I guess not, I'll try to make my mod compatible in the 0.5 update

**Comment by ITsMrToad** [comment]
I still failed to make the mod compatible with sinytra :(


But you can try to use the [original](https://modrinth.com/mod/ebe)

**Comment by Krimatoria** [comment]
It seems to me that the original does not work, the settings buttons do not appear in the appendix and I do not know how to check if the mod has any effect.

**Comment by ITsMrToad** [comment]
If the settings do not appear, then most likely the mod is not working. 

Why do you need the Sinytra Connector?

**Comment by Krimatoria** [comment]
> If the settings do not appear, then most likely the mod is not working.
> 
> Why do you need the Sinytra Connector?

Well, I have a mod for statistics from Fabric and a few more mods for mobs that are not on forge, a couple of optimization mods are also from Fabric. The connector has greatly expanded the possibilities. I originally set it for Aliens. But they are too broken with shaders, and there are still too many bugs there.

**Comment by CapoFantasma97** [comment]
Sinytra/Connector#1402

**Comment by vinnyg0621** [comment]
yeah please keep trying hard to fix it. I also use forge 1.20 with fabric mods too!

**Comment by vinnyg0621** [comment]
it's too bad you couldn't make it compatible. but keep trying and don't give up, I believe in you!

**Comment by ITsMrToad** [comment]
I have good news! I managed to realize compatibility with Sinytra! However, it's not stable yet. Maybe next week 0.8 will be released!

**Comment by vinnyg0621** [comment]
all right

**Comment by ITsMrToad** [comment]
0.8 update is almost done, it will require toadlib due to new features.

Last tests...

**Comment by ITsMrToad** [comment]
EBE 0.8 is out!

**Comment by CapoFantasma97** [comment]
It still crashes https://mclo.gs/o1ZuQkn

**Comment by CapoFantasma97** [comment]
> It still crashes [mclo.gs/o1ZuQkn](https://mclo.gs/o1ZuQkn)

Snooped around and found you added a guide on that. It's annoying that we have to generate and edit the config file before adding connector, but at least it doesn't crash anymore.

On a side note, I wonder the comparison between this and the original which launches via Connector. Neither of the two seem to be able to open the config page (the one present on the original when running on Fabric).

**Comment by vinnyg0621** [comment]
i reported the crash that still happens

**Comment by ITsMrToad** [comment]
> It still crashes https://mclo.gs/o1ZuQkn

Have you done everything you need to do from the pinned issue?

**Comment by Krimatoria** [comment]
config created only when changing one of the EBE settings in the graphics settings. When the API Fabric+Connector is enabled, the config will not be created either. You need to turn it off first. Everything works) True, the beds in front and back were invisible, but they are drawn from below and above.
