### ISSUE TITLE
[Question] What benefits does this mod offer past using the original with Connector? 

### ISSUE THREAD

**Issue by Sshmoob** [ITsMrToad/EBEReforged#2]
I don't know if you know this, but EnhancedBlockEntities already worked with Connector, so it could already be used on Forge. I'm wondering if there are any features your port adds that go past just using Connector with the original?

**Comment by ITsMrToad** [comment]
1.20-1.20.4 EBE uses ARRP. My mod uses the new system ported from 1.20.6. The original mod with connector uses more mixins(my mod uses forge events).

In addition, connector is not compatible with many mods. 

And as far as I know the original does not work on forge/neoforge, here is a [issue](https://github.com/ITsMrToad/EBEReforged/issues/1) related to this.
