### ISSUE TITLE
Update to 0.8 and Sinytra integration

### ISSUE THREAD

**Issue by ITsMrToad** [ITsMrToad/EBEReforged#3]
### Update to 0.8:
- Install ToadLib
- Delete old config file(Optional)
### Sinytra integration
Method 1:
- Create/Generate config of ebe().
- Change value of `forceMFAPICompat`(in config) to `true`

Method 2(If config file exists):
- Add to cfg `forceMFAPICompat=true`(Before forceResourcePackCompat)

- Install connector and FFAPI(Forgified fabric API)

**Don't forget to disable `forceMFAPICompat` in the config before removing the connector**

**Comment by ITsMrToad** [comment]
0.9 version does not require any actions to integrate sinytra.

**Comment by mateus3c** [comment]
If you dont mind me asking, whats the difference between using your fork to using the original mod with sinytra?

**Comment by ITsMrToad** [comment]
> If you dont mind me asking, whats the difference between using your fork to using the original mod with sinytra?

Issue with answers #2 
Also, i'm not sure the original with sinytra works properly.
