### ISSUE TITLE
EBE 0.8.1 still crashes with FFAPI on 1.20.1

### ISSUE THREAD

**Issue by vinnyg0621** [ITsMrToad/EBEReforged#4]
[client crash here
](https://hastebin.com/share/gotolalaqo.csharp)
btw, client crashes are the most annoying ones.

**Comment by ITsMrToad** [comment]
Read pinned issue.

**Comment by SeanChengN** [comment]
https://github.com/ITsMrToad/EBEReforged/issues/3
works
