### ISSUE TITLE
cookingforblockheads mod incompatibility

### ISSUE THREAD

**Issue by Cold4blood** [ITsMrToad/EBEReforged#5]
place a this mod blocks will cause a crash.

[crash-2024-09-26_01.25.55-client.txt](https://github.com/user-attachments/files/17134829/crash-2024-09-26_01.25.55-client.txt)

**Comment by zhiquawa** [comment]
I'm having the same problem.On the ATM9,includeing **ebe oculus and cookingforblockheads** at the same time.
[crash-2024-10-05_01.31.20-client.txt](https://github.com/user-attachments/files/17264700/crash-2024-10-05_01.31.20-client.txt)

**Comment by ITsMrToad** [comment]
I was probably able to fix this in 0.9.1...

**Comment by Cold4blood** [comment]
Thank you for your efforts.
